version: 2.1

orbs:
  rn: react-native-community/react-native@5.6.2
  android: circleci/android@1.0.3

# - rn/yarn_install
# fails with Error untarring cache: Error extracting tarball /var/folders/bq/mjrgbpkx5h1g_b22fpv0tlzc0000gn/T/cache376822577 : tmp/yarn/: Cannot extract through symlink tmp/yarn tmp/yarn/v6/: Cannot extract through symlink tmp/yarn/v6 tmp/yarn/v6/.tmp/: Cannot extract through symlink tmp/yarn/v6/.tmp tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel/code-frame/: Cannot extract: exit status 1
# that is why we use yarn install --frozen-lockfile but that is SLOW! help us to fix this!

jobs:
  analyse_js:
    executor:
      name: rn/linux_js
      node_version: '14.17.0'
    steps:
      - checkout
      # - rn/yarn_install
      # fails with Error untarring cache: Error extracting tarball /var/folders/bq/mjrgbpkx5h1g_b22fpv0tlzc0000gn/T/cache376822577 : tmp/yarn/: Cannot extract through symlink tmp/yarn tmp/yarn/v6/: Cannot extract through symlink tmp/yarn/v6 tmp/yarn/v6/.tmp/: Cannot extract through symlink tmp/yarn/v6/.tmp tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel/code-frame/: Cannot extract: exit status 1
      - run:
          command: export TZ='Asia/Singapore'
          name: Set Time Zone
      - run:
          command: yarn install --frozen-lockfile
          name: yarn install
#      - run:
#          command: yarn lint
#          name: Run ESLint
      #      - run:
      #          command: yarn flow
      #          name: Flow
      - run:
          command: NODE_OPTIONS=--max_old_space_size=4000 yarn test:coverage --watchAll=false
          name: Jest
      - store_artifacts:
          path: artifact
      - store_artifacts:
          path: test-report.xml
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  e2e_release_ios:
    executor:
      name: rn/macos
      xcode_version: '13.1.0'
    steps:
      - attach_workspace:
          at: .
      #      - checkout
      - run:
          name: install applesimutils
          command: |
            HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
            HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
      - rn/ios_simulator_start:
          device: 'iPhone 13 Pro Max'
      # - rn/yarn_install
      #      - run:
      #          command: yarn install --frozen-lockfile
      #          name: yarn install
      - rn/pod_install:
          pod_install_directory: 'ios'
      - run:
          command: curl https://raw.githubusercontent.com/facebook/react-native/6334ac35ac3cbc2c84b2d46d46ec118bf9bf714d/scripts/find-node.sh > node_modules/react-native/scripts/find-node.sh
          name: fix issue with nvm # will be fixed in RN 67 (https://github.com/react-native-community/upgrade-support/issues/138)
      - run:
          command: yarn detox-build:ios-release
          name: build app for e2e tests
      - run:
          command: yarn detox-test:ios-release
          name: run e2e tests
      - store_artifacts:
          path: ./e2e/artifacts

  e2e_release_android:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - attach_workspace:
          at: .
      #      - checkout
      - run:
          name: change default node version
          command: |
            nvm install v15.11.0
            nvm alias default v15.11.0
            echo 'export PATH=/opt/circleci/.nvm/versions/node/v15.11.0/bin:$PATH' >> $BASH_ENV
      - android/create-avd:
          avd-name: EMU_API_30
          system-image: system-images;android-29;default;x86
          install: true
      - android/start-emulator:
          avd-name: EMU_API_30
          no-window: true
          restore-gradle-cache-prefix: v1a
          post-emulator-launch-assemble-command: "pwd"
      - android/disable-animations
      - run:
          command: npm install --global yarn
          name: install yarn
      #      - run:
      #          command: yarn install --frozen-lockfile
      #          name: yarn install
      - run:
          command: yarn detox-build:android-release
          name: build app for e2e tests
      - run:
          command: yarn detox-test:android-release
          name: run e2e tests
      - store_artifacts:
          path: ./e2e/artifacts

#  publish:
#    executor:
#      name: rn/linux_js
#      node_version: '14.17.0'
#    steps:
#      - checkout
#      # - rn/yarn_install
#      # fails with Error untarring cache: Error extracting tarball /var/folders/bq/mjrgbpkx5h1g_b22fpv0tlzc0000gn/T/cache376822577 : tmp/yarn/: Cannot extract through symlink tmp/yarn tmp/yarn/v6/: Cannot extract through symlink tmp/yarn/v6 tmp/yarn/v6/.tmp/: Cannot extract through symlink tmp/yarn/v6/.tmp tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel/: Cannot extract through symlink tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel tmp/yarn/v6/npm-@babel-code-frame-7.8.3-33e25903d7481181534e12ec0a25f16b6fcf419e-integrity/node_modules/@babel/code-frame/: Cannot extract: exit status 1
#      - run:
#          command: yarn install --frozen-lockfile
#          name: yarn install
#      - run:
#          command: npx semantic-release
#          name: Publish to NPM


workflows:
  test:
    jobs:
      - analyse_js
      - e2e_release_ios:
          requires:
            - analyse_js
      - e2e_release_android:
          requires:
            - analyse_js
#      - publish:
#          requires:
#            - e2e_release_android
#            - e2e_release_ios
#          filters:
#            branches:
#              only: master
