version: 2.1

orbs:
  rn: react-native-community/react-native@6.8.1
  android: circleci/android@2.0.0
  mac: circleci/macos@2.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - rn/yarn_install
      - run:
          command: echo "yarn lint"
          name: Run linter
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:16.14.2
        environment:
          TZ: "Asia/Singapore"
    #    parallelism: 4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          # uncomment below if parallelism needed
          #          command: |
          #            TEST=$(circleci tests glob "./src/**/*.spec.tsx" | circleci tests split --split-by=timings)
          #            NODE_OPTIONS=--max_old_space_size=4096 JEST_JUNIT_OUTPUT_DIR="./test-results" JEST_JUNIT_OUTPUT_NAME="junit-${CIRCLE_NODE_INDEX}.xml" yarn test:coverage --watchAll=false --maxWorkers=4 $TEST
          command: NODE_OPTIONS=--max_old_space_size=4096 JEST_JUNIT_OUTPUT_DIR="./test-results" JEST_JUNIT_OUTPUT_NAME="junit-${CIRCLE_NODE_INDEX}.xml" yarn test:coverage --watchAll=false --maxWorkers=4
          name: Jest
      - store_artifacts:
          path: ~/project/coverage
      - store_artifacts:
          path: ~/project/test-report.xml
      - store_test_results:
          path: ~/project/test-results
#      - persist_to_workspace:
#          root: .
#          paths:
#            - test-report.xml

  sonar-qube:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: echo "sonar qube"
#          NODE_OPTIONS=--max_old_space_size=4096 yarn run sonar-scanner -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_TOKEN}
          name: Static code analysis
      - store_artifacts:
          path: ~/project/artifact


  build_ios_release:
    executor:
      name: rn/macos
      xcode_version: '13.3.0'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - rn/pod_install
      - run:
          command: npm run detox-build:ios-release
          name: Build iOS release for e2e tests
      - persist_to_workspace:
          root: .
          paths:
            - ios

  build_android_release:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.03.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          command: npm run detox-build:android-release
          name: Build Android release for e2e tests
      - android/save-gradle-cache
      - android/save-build-cache
      - persist_to_workspace:
          root: .
          paths:
            - android


  test_ios_release:
    parallelism: 4
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install AppleSimulatorUtils
          command: |
            HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
            HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
#      - mac/preboot-simulator:
#          device: 'iPhone 13 Pro Max'
#          version: '15.2'
#          platform: "iOS"
      - rn/ios_simulator_start:
          device: 'iPhone 13 Pro Max'
      - run:
          command: npx detox clean-framework-cache && npx detox build-framework-cache
          name: Clean Detox Cache
      - run:
          command: |
            circleci tests glob "e2e/tests/*.e2e.js" | circleci tests split --split-by=timings
            yarn detox-test:ios-release
          name: Run E2E Tests
      - store_test_results:
          path: ~/project/e2e/artifacts/ios-junit.xml
      - store_artifacts:
          path: ~/project/e2e/artifacts

  test_android_release:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 202102-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - android/create-avd:
          avd-name: EMU_API_30
          system-image: system-images;android-29;default;x86
          install: true
      - android/start-emulator:
          avd-name: EMU_API_30
          no-window: true
          restore-gradle-cache-prefix: v1a
          post-emulator-launch-assemble-command: "pwd"
      - android/disable-animations
      - run:
          command: npx detox clean-framework-cache && npx detox build-framework-cache
          name: Clean Detox Cache
      - run:
          command: npm run detox-test:android-release
          name: Run E2E Tests
      - store_test_results:
          path: ~/project/e2e/artifacts/android-junit.xml
      - store_artifacts:
          path: ~/project/e2e/artifacts

workflows:
  "Pipeline":
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - sonar-qube:
          requires:
            - test
      - build_ios_release:
          requires:
            - build
            - test
            - sonar-qube
#      - build_android_release:
#          requires:
#            - sonar-qube
      - test_ios_release:
          requires:
            - build_ios_release
#      - test_android_release:
#          requires:
#            - build_android_release
