version: 2.1

orbs:
  rn: react-native-community/react-native@6.8.1

jobs:
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '14.17.0'
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .

  analyse_js:
    executor:
      name: rn/linux_js
      node_version: '14.17.0'
    steps:
      - attach_workspace:
          at: .
      - run:
          command: export TZ='Asia/Singapore'
          name: Set Time Zone
          #not working properly
      - rn/yarn_install
#      - run:
#          command: yarn install --frozen-lockfile
#          name: yarn install
# not configured
      # - run:
      #     command: yarn lint
      #     name: Run ESLint
#      - run:
#          command: yarn flow
#          name: Flow
      - run:
          command: NODE_OPTIONS=--max_old_space_size=4000 yarn test:coverage --watchAll=false
          name: Jest

workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
#      - rn/android_build:
#          build_type: debug
#          name: build_android_debug
#          project_path: android
#          requires:
#            - analyse_js
      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires:
            - analyse_js
      - rn/android_test:
          detox_configuration: android.emu.release
          requires:
            - build_android_release
#      - rn/ios_build:
#          build_configuration: Release
#          device: iPhone 11
#          name: build_ios_release
#          node_version: '14'
#          project_path: ios/myexpo.xcodeproj
#          requires:
#            - analyse_js
#          scheme: myexpo
      - rn/ios_build_and_test:
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: 'iPhone 13 Pro Max'
          node_version: '14'
          project_path: ios/myexpo.xcodeproj
          requires:
            - analyse_js
          scheme: myexpo
#      - fastlane_android_release:
#          requires:
#            - rn/android_test
#      - fastlane_ios_release:
#          requires:
#            - rn/ios_build_and_test
