version: 2.1

jobs:
  checkout_and_build:
    macos:
      xcode: "13.3.0"
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  detox_ios:
    macos:
      xcode: "13.3.0"
    steps: # a series of commands to run
      - run: |
          npx nod-install
          yarn detox-build:ios-release
          yarn detox-text:ios-release

workflows:
  build_and_test:
    jobs:
      - checkout_and_build
      - detox_ios
