version: 2.1
jobs:
  build:
    macos:
      xcode: "13.3.0"

    working_directory: ~/repo

    steps:
      - checkout

      # Set up environment
      - run: npm install -g yarn
      - run: yarn
      # - run: npm install -g detox-cli
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npx pod-install

        # run unit tests
      # - run: yarn install
      # - run: yarn test

      # run E2E tests
      - run : yarn build:ios-release
      - run : yarn test:ios-release
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /repo/e2e/artifacts
