version: 2.1

jobs:
  checkout_and_build:
    macos:
      xcode: "13.3.0"
    steps: # a series of commands to run
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  detox_ios:
    macos:
      xcode: "13.3.0"
    steps: # a series of commands to run
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: |
          npx pod-install
          yarn detox-build:ios-release
          yarn detox-text:ios-release

workflows:
  build_and_test:
    jobs:
      - checkout_and_build
      - detox_ios:
          requires:
            - checkout_and_build
