version: 2.1

commands:
  install_dependencies:
    steps:
      - restore_cache:
          keys:
            - node_modules-v1-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node_modules-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  ios_cache:
    steps:
      - restore_cache:
          keys:
            - ios-v1-{{ checksum "ios/Podfile.lock" }}
      - run: |
          npx pod-install
          yarn build:ios-release
      - save_cache:
          key: ios-v1-{{ checksum "ios/Podfile.lock" }}
          paths:
            - ios
executors:
  mac:
    macos:
      xcode: "13.3.0"

jobs:
  checkout_and_build:
    executor: mac
    steps:
      - checkout
      - install_dependencies
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  detox_ios_build:
    executor: mac
    steps:
      - attach_workspace:
            at: .
      - ios_cache
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  detox_ios_test:
    executor: mac
    steps:
      - attach_workspace:
            at: .
      - run: yarn test:ios-release

workflows:
  build_and_test:
    jobs:
      - checkout_and_build
      - detox_ios_build:
          requires:
            - checkout_and_build
      - detox_ios_test:
          requires:
            - detox_ios_build
