name: e2e

on: [ push ]

jobs:
  ios_build_and_test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npx pod-install

        # run E2E tests
      - run: yarn build:ios-release
      - run: yarn test:ios-release

  android_build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile

      - name: Download Android Emulator Image
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-30;default;x86_64"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -f -n Pixel_API_28_AOSP --device "Nexus 5X" -k "system-images;android-30;default;x86_64"
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Build for detox
        run: |
          yarn build:android-release

      - name: Android Emulator
        timeout-minutes: 10
        continue-on-error: true
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd emu -no-audio -no-snapshot -no-window &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices
          echo "Emulator started"

      - name: Android Detox
        run: yarn test:android-release

