name: iOS

on: [ push ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install -g yarn
      - run: yarn
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npx pod-install

        # run E2E tests
      - run: yarn build:ios-release
      - run: yarn test:ios-release
